### ISSUE TITLE
Themes are not working

### ISSUE THREAD

**Issue by tastyminerals** [codebrainz/geany-themes#44]
I have cloned this repo and ran `install.sh` script which correctly created **colorschemes** dir in `~/.config/geany/`. However if I open **geany** and try to find where I can actually set these themes I cannot find the option anywhere.

Geany version: 1.23.1, distro: Ubuntu trusty

Also, please write proper instructions on how to select and set a theme.

**Comment by codebrainz** [comment]
View->Change Color Scheme

**Comment by tastyminerals** [comment]
Slap! You're right, I was following some other instruction which stated that I should go to preferences > editor...

**Comment by codebrainz** [comment]
Many people have this problem, we really need to move these options into Preferences dialog where people expect. (Ex. see https://github.com/geany/geany-themes/issues/6)

**Comment by vannaxpjf** [comment]
I'm running Geany 2.0 on OML Rock 6.
I have put a couple of themes in the ~/.config/geany/colorschemes/ directory.
They still do not show up in the View/Change Color Scheme dialogue.
Any ideas?
