### ISSUE TITLE
Why Geany doesn't exactly use what is set in marker_search?

### ISSUE THREAD

**Issue by jpfleury** [codebrainz/geany-themes#5]
**Note:** feel free to tell me if this issue tracker is not the best way to ask questions.

I noticed that the background color really used in Geany to mark searches is never the exact color set in `marker_search` by color schemes, as if a kind of translucency was automatically set. For example, see the following screenshot:

http://www.jpfleury.net/depot-fichiers/png/geany-themes-gedit-cpp.png

Color scheme with my patch sets:

```
marker_line=0x000000;0xffff00
marker_search=marker_line
```

but we see in the screenshot that Geany really uses color `0xffffc3` instead of `0xffff00`.

Same thing with other color schemes. For example, GitHub scheme sets:

```
marker_search=;0xc0c0c0
```

but Geany really uses `0xebebf0`.

I tried to play with `marker_translucency`, but it doesn't change anything.

Do you have any idea why it happens?

**Comment by exebook** [comment]
Can we open this as a feature request to add <the right word>_translucency?
![selection_185](https://cloud.githubusercontent.com/assets/3821217/24072327/c6ef4b2c-0bf6-11e7-92d0-2b595ef32596.jpg)
